### ISSUE TITLE
How to get the Kanji count of Tanzaku?

### ISSUE THREAD

**Issue by carlosbdw** [usagimaru/Tanzaku#1]
Hello , I want to make a reader app by using Tanzaku ,if I could make sure the font size and the view size , how could I know the count of Kanji in on page ? Any idea? Thank you !

**Comment by usagimaru** [comment]
Tanzaku can not calculate the number of displaying characters. I do not plan to implement that function, but if I find that the mechanism is simple, I will consider implementing it. Thank you.
